backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "public/images/uploads"
site_url: https://wasimraja.netlify.app
collections:
  # blog posts
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Post' # Used in the UI
    folder: 'src/pages/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { 
          label: 'Publish Date',
          name: 'date', 
          widget: 'datetime',
          date_format: "DD.MM.YYYY",
          time_format: false 
        }
      - {
          label: 'Author',
          name: 'author',
          widget: 'string',
          default: 'Wasim Raja',
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Cover', name: 'cover', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'projects' # Used in routes, e.g., /admin/collections/blog
    label: 'Projects' # Used in the UI
    folder: 'src/data' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: json
    slug: '{{fields.name}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: Project
        name: project
        widget: list
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Summary', name: 'summary', widget: 'text' }
