backend:
  name: test-repo
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "public/images/uploads"
site_url: https://wasimraja.netlify.app
collections:
  # Our blog posts
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Post' # Used in the UI
    folder: 'src/pages/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', date_format: "DD.MM.YYYY", time_format: false }
      - {
          label: 'Author',
          name: 'author',
          widget: 'string',
          default: 'Wasim Raja',
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }